#!/usr/bin/env bash

command cd $HOME
_xdg_config_home=${XDG_CONFIG_HOME:-$HOME/.config}
_xdg_data_home=${XDG_DATA_HOME:-$HOME/.local/share}
command mkdir -p ${_xdg_config_home} ${_xdg_data_home}

if [[ ! -d ${_xdg_config_home}/dotfiles ]] && (( $UID == 0 )); then
  ln -s ~kshenoy/.config/dotfiles ${_xdg_config_home}/dotfiles
fi
if [[ ! -d ${_xdg_config_home}/dotfiles-priv ]]; then
  if (( $UID == 0 )); then
    ln -s ~kshenoy/.config/dotfiles-priv ${_xdg_config_home}/dotfiles-priv
  else
    git clone https://github.com/kshenoy/dotfiles-priv ${_xdg_config_home}/dotfiles-priv
  fi
fi

ln -svTf ${_xdg_config_home}/dotfiles{-priv,}/bash/work
ln -svTf ${_xdg_config_home}/dotfiles{-priv,}/scripts/amd
ln -svTf ${_xdg_config_home}/dotfiles{-priv,}/vim/pack/rc_local

mkdir -p ${_xdg_config_home}
ln -svTf ${_xdg_config_home}/dotfiles/bash/bashrc           ~/.bashrc
ln -svTf ${_xdg_config_home}/dotfiles/ctags                 ~/.ctags
ln -svTf ${_xdg_config_home}/dotfiles/vim                   ~/.config/nvim
ln -svTf ${_xdg_config_home}/dotfiles/vim                   ~/.vim
ln -svTf ${_xdg_config_home}/dotfiles/xinitrc               ~/.xinitrc
ln -svTf ${_xdg_config_home}/dotfiles/Xresources            ~/.Xresources
ln -svTf ${_xdg_config_home}/dotfiles/fzf/fzf.bash          ~/.fzf.bash
# ln -svTf ${_xdg_config_home}/dotfiles/awesome             ~/.config/awesome
# ln -svTf ${_xdg_config_home}/dotfiles/i3                  ~/.config/i3

mkdir -p ~/.emacs.d
ln -svTf ${_xdg_config_home}/dotfiles/emacs.d/custom.el     ~/.emacs.d/custom.el
ln -svTf ${_xdg_config_home}/dotfiles/emacs.d/snippets      ~/.emacs.d/snippets
ln -svTf ${_xdg_config_home}/dotfiles-priv/emacs.d/work.el  ~/.emacs.d/work.el

if [[ ! -d ${_xdg_config_home}/base16-shell ]]; then
  if (( $UID == 0 )); then
    ln -s ~kshenoy/.config/base16-shell ${_xdg_config_home}/base16-shell
  else
    git clone https://github.com/chriskempson/base16-shell.git ${_xdg_config_home}/base16-shell
  fi
fi

if [[ ! -d ${_xdg_config_home}/base16-fzf ]]; then
  if (( $UID == 0 )); then
    ln -s ~kshenoy/.config/base16-fzf ${_xdg_config_home}/base16-fzf
  else
    git clone https://github.com/nicodebo/base16-fzf ${_xdg_config_home}/base16-fzf
  fi
fi

mkdir -p ${_xdg_config_home}/git
ln -svTf ${_xdg_config_home}/dotfiles/gitignore             ${_xdg_config_home}/git/ignore

mkdir -p ~/.ssh
ln -svTf ${_xdg_config_home}/dotfiles-priv/ssh/config       ~/.ssh/config

mkdir -p ~/.unison
ln -svTf ~${_xdg_config_home}/dotfiles/unison/dotfiles.prf  ~/.unison/dotfiles.prf

mkdir -p ~/bin
ln -svTf ${_xdg_config_home}/dotfiles/scripts/vim_merge     ~/bin/vim_merge
ln -svTf ${_xdg_config_home}/dotfiles/scripts/emacs_daemon  ~/bin/emacs_daemon
ln -svTf ${_xdg_config_home}/dotfiles/scripts/rgf           ~/bin/rgf
ln -svTf ${_xdg_config_home}/dotfiles/scripts/vile          ~/bin/vile

if (( $UID == 0 )); then
  ln -s ~kshenoy/.local/share/bash_history ${_xdg_data_home}/bash_history
else
  mkdir -p ${_xdg_data_home}/bash_history
fi
command rm -i ~/.bash_history 2> /dev/null

# Create a pipe. Woo!
if [[ ! -p ~/pipe ]]; then
  mkfifo ~/pipe
fi
