#!/usr/bin/env bash

_root=/media/$(whoami)/LinData
_dropbox=~/Dropbox

if [[ ! -d "$_root" ]]; then
  echo "Folder '$_root' not found"
  exit 1
fi

for i in $(command ls -1 "$_root"); do
  if [[ ! $i =~ lost ]]; then
    ln -svTf "$_root/$i" ~/$i
  fi
done
mkdir -p ~/.config ~/.local/share ~/.ssh ~/.unison ~/bin

ln -svTf "$_dropbox"/Documents/Notes  ~/Notes
ln -svTf "$_dropbox"/Config/dotfiles  ~/.dotfiles
ln -svTf "$_dropbox"/Config/Fonts     ~/.local/share/fonts

ln -svTf ~/.dotfiles/awesome                 ~/.config/awesome
ln -svTf ~/.dotfiles/bash/bash_logout        ~/.bash_logout
ln -svTf ~/.dotfiles/bash/bashrc             ~/.bashrc
ln -svTf ~/.dotfiles/bash/bashrc_local-home  ~/.bashrc_local
ln -svTf ~/.dotfiles/bash/history            ~/.history_bash
ln -svTf ~/.dotfiles/ctags                   ~/.ctags
ln -svTf ~/.dotfiles/dircolors               ~/.dircolors
ln -svTf ~/.dotfiles/emacs.d                 ~/.emacs.d
ln -svTf ~/.dotfiles/git/gitconfig           ~/.gitconfig
ln -svTf ~/.dotfiles/git/gitignore_global    ~/.gitignore_global
ln -svTf ~/.dotfiles/i3                      ~/.config/i3
ln -svTf ~/.dotfiles/ssh/config              ~/.ssh/config
ln -svTf ~/.dotfiles/tmux/tmux.conf          ~/.tmux.conf
ln -svTf ~/.dotfiles/unison/dotfiles.prf     ~/.unison/dotfiles.prf
ln -svTf ~/.dotfiles/vim                     ~/.config/nvim
ln -svTf ~/.dotfiles/vim                     ~/.vim
ln -svTf ~/.dotfiles/xinitrc                 ~/.xinitrc
ln -svTf ~/.dotfiles/Xresources              ~/.Xresources

ln -svTf ~/.dotfiles/scripts/vipe            ~/bin/vipe
ln -svTf ~/.dotfiles/scripts/vim_merge       ~/bin/vim_merge
ln -svTf ~/.dotfiles/scripts/wim             ~/bin/wim

# Create a pipe. Woo!
if [[ ! -p ~/pipe ]]; then
  mkfifo ~/pipe
fi
