#!/usr/bin/env bash

command cd $HOME
_xdg_config_home=${XDG_CONFIG_HOME:-$HOME/.config}
_xdg_data_home=${XDG_DATA_HOME:-$HOME/.local/share}

mkdir -p ${_xdg_config_home}{,/git}

ln -svTf ${_xdg_config_home}/dotfiles     ~/.dotfiles
ln -svTf ~/.dotfiles/bash/bashrc          ~/.bashrc
ln -svTf ~/.dotfiles/ctags                ~/.ctags
ln -svTf ~/.dotfiles/vim                  ~/.config/nvim
ln -svTf ~/.dotfiles/vim                  ~/.vim
ln -svTf ~/.dotfiles/xinitrc              ~/.xinitrc
ln -svTf ~/.dotfiles/Xresources           ~/.Xresources
ln -svTf ~/.dotfiles/fzf/fzf.bash         ~/.fzf.bash
# ln -svTf ~/.dotfiles/awesome            ~/.config/awesome
# ln -svTf ~/.dotfiles/i3                 ~/.config/i3

mkdir -p ~/.ssh
ln -svTf ~/.dotfiles/ssh/config           ~/.ssh/config

mkdir -p ~/.unison
ln -svTf ~/.dotfiles/unison/dotfiles.prf  ~/.unison/dotfiles.prf

mkdir -p ~/bin
ln -svTf ~/.dotfiles/scripts/vim_merge   ~/bin/vim_merge
# ln -svTf ~/.dotfiles/scripts/wim       ~/bin/vim

mkdir -p ${_xdg_data_home}{,/bash_history}
command rm -i ~/.bash_history 2> /dev/null
ln -svTf ${_xdg_data_home}/bash_history  ~/.bash_history

# Create a pipe. Woo!
if [[ ! -p ~/pipe ]]; then
  mkfifo ~/pipe
fi
