#!/usr/bin/env bash

unset -f alert
alert() {
# Description:
#   "alert" for long running commands
#   NOTE: This must be used as a function to have access to the history via the fc command
#
# Syntax:
#   Use like so: sleep 10 && alert

  # Pick up display message if provided as argument. If not show the last command that was run
  local _msg=${1:-$(fc -nl -1 | sed -e 's/^\s*[0-9]\+\s*//' -e 's/[;&|]\+\s*alert$//')}

  # Add TMUX information if available
  if [[ -n $TMUX ]]; then
    _msg="$(tmux display-message -p "[#S:#I.#P]") ${_msg}"
  else
    _msg="[$$] ${_msg}"
  fi

  # Indicate normal completion or error
  local _icon=$( (($? == 0)) && echo terminal || echo error)

  notify-send --urgency=low -i ${_icon} "${_msg}"
}
