" .gvimrc file


"
" Mouse pointer specific options
"
  " Enable mouse in (c)ommand, (i)nsert, (n)ormal, (v)isual or (a)ll modes
  set mouse=a


"
" GUI
"
  " Set Font
  if has('unix')
    set guifont=
    set guifont+=Hack\ 9
    set guifont+=MesloLGLDZ\ Nerd\ Font\ 8
    set guifont+=Monospace\ 8
    set linespace=3
  elseif has('win32')
    set guifont=
    set guifont+=Hack:h9:cANSI:qDRAFT
    set guifont+=Consolas:h9:cANSI
    set linespace=3
  endif

  set guioptions-=b    " Disable horizontal scrollbar
  set guioptions-=l    " Disable left-hand scrollbar
  set guioptions-=L    " Disable left-hand vertically split window scrollbar
  set guioptions-=m    " Disable menu-bar
  set guioptions-=r    " Disable right-hand scrollbar
  set guioptions-=R    " Disable right-hand vertically split window scrollbar
  set guioptions-=T    " Disable toolbar

  " Disable <Alt> key shortcuts used to access menu
  set winaltkeys=no

  " Make 'File Open' use current directory
  set browsedir=buffer

  if &diff
    set background=light
    colorscheme solarized
  else
    set background=dark
    colorscheme base16-eighties
  endif

  " Light colorschemes
  " set background=light
  " colorscheme sol
  " colorscheme solarized

  " Dark colorschemes
  " set background=dark
  " colorscheme base16-ocean
  " colorscheme one
