set mouse=a

if has('unix')
  set guifont=IosevkaTerm\ Nerd\ Font\ Mono\ 10
  set guifont+=Monospace\ 10
else
  set guifont=Iosevka:h9:cANSI:qDRAFT
  set guifont+=Consolas:h9:cANSI
endif
set linespace=2

set guioptions-=b
set guioptions-=l
set guioptions-=L
set guioptions-=m
set guioptions-=r
set guioptions-=R
set guioptions-=T
set winaltkeys=no
set browsedir=buffer
