" .gvimrc file


"
" 7.  MULTIPLE TAB PAGES
"
set guitablabel=%{utils#GuiTabLabel()}
set guitabtooltip=%{utils#GuiTabToolTip()}


"
" 8.  TERMINAL                                                                                                      {{{1
"
set esckeys                                                                    " Allow use of cursor keys in insert mode

" Setup default highlight groups for the cursors
for i in ['Normal', 'Visual', 'Command', 'Insert', 'Replace']
  if !hlexists(i.'Cursor')
    execute 'highlight link ' . i . 'Cursor Cursor'
  endif
endfor
set guicursor=n:block-NormalCursor/lCursor
set guicursor+=v:block-VisualCursor/lCursor
set guicursor+=c:ver25-CommandCursor/lCursor
set guicursor+=ve:ver35-VisualCursor/lCursor
set guicursor+=o:hor20-CommandCursor/lCursor
set guicursor+=i-ci:ver25-InsertCursor/lCursor
set guicursor+=r-cr:hor20-ReplaceCursor/lCursor
set guicursor+=sm:block-InsertCursor-blinkwait175-blinkoff150-blinkon175

"
" 9. USING THE MOUSE
"
set mouse=a                                                                                  " Enable mouse in all modes


"
" 10. GUI
"
  " Set Font
  if g:env ==? 'linux'
    " Note that this doesn't include Cygwin or Mingw
    set guifont=
    set guifont+=IosevkaTerm\ Nerd\ Font\ Mono\ 10
    set guifont+=Monospace\ 10
    set linespace=2
  elseif g:env ==? 'windows'
    set guifont=
    set guifont+=Iosevka:h9:cANSI:qDRAFT
    set guifont+=Consolas:h9:cANSI
    set linespace=2
  endif

  set guioptions-=b    " Disable horizontal scrollbar
  set guioptions-=l    " Disable left-hand scrollbar
  set guioptions-=L    " Disable left-hand vertically split window scrollbar
  set guioptions-=m    " Disable menu-bar
  set guioptions-=r    " Disable right-hand scrollbar
  set guioptions-=R    " Disable right-hand vertically split window scrollbar
  set guioptions-=T    " Disable toolbar

  " Disable <Alt> key shortcuts used to access menu
  set winaltkeys=no

  " Make 'File Open' use current directory
  set browsedir=buffer
