" Organized as per sections in ":options"

" When vim is started with -u option, the $MYVIMRC variable does not get set. In that case, we manually construct the
" entire runtimepath by adding the system vimfiles and my vimfiles directory to the runtimepath. This allows me to
" start vim on somebody else's comp using 'vim -u <path/to/my/vimrc> -U <path/to/my/gvimrc>', ignore their local
" vimfiles and have all of my plugins available as well!
let g:dotvim = expand('<sfile>:p:h')
if (strlen($MYVIMRC) == 0)
  let &rtp=expand($VIMRUNTIME)
  let s:vimfiles=substitute($VIMRUNTIME, "/[^/]*$", "/vimfiles", "")
  for i in [s:vimfiles, g:dotvim]
    execute 'let &rtp="' . i . ',' . &rtp . ',' . i . '/after"'
  endfor
endif

" Set g:env
execute "source " . expand(g:dotvim . "/pack/utils/start/utils/plugin/utils.vim")
call utils#SetEnvInfo()


" Placing at top so all files can use it no matter in which order they get sourced
let mapleader = "\<Space>"
let maplocalleader = "\\"


"
" 1.  IMPORTANT                                                                                                     {{{1
"
set nocompatible                                                       " Doesn't constrain VIM to be fully VI compatible

if filereadable(glob(g:dotvim . '/bundles.vim'))
  execute 'source ' . g:dotvim . '/bundles.vim'
endif
filetype plugin indent on

"
" 2.  MOVING AROUND, SEARCHING AND PATTERNS                                                                         {{{1
"
set nostartofline                             " Prevent cursor from jumping to start of line in case of certain commands
set path=.,/usr/local/include,/usr/include,**;
set autochdir                                                                       " Change directory to file in buffer
set incsearch                                                                          " Incremental search highlighting
set ignorecase                                                                              " Ignore Case when searching
set smartcase                                               " Override ignorecase when pattern has upper case characters


"
" 4.  DISPLAYING TEXT                                                                                               {{{1
"
set scrolloff=3                                                       " Number of screen lines to show around the cursor
set sidescroll=3
set sidescrolloff=10
set cmdheight=2                                                                                    " Command area height
set encoding=utf-8                                                                                  " Character encoding
set list                                                                              " Display non-printable characters
set listchars=tab:»\ ,extends:›,precedes:‹,nbsp:·,trail:·
"set listchars=eol:$,trail:…,tab:>-,extends:>,precedes:<,conceal:+
"set fillchars=stl:^,stlnc:-,vert:\│,fold:-,diff:-
augroup set_list
  au!
  autocmd BufEnter    * if (&ft == 'help' || &bt == 'nofile') | setlocal nolist | endif
  autocmd InsertEnter * set listchars-=trail:…
  autocmd InsertLeave * set listchars+=trail:…
augroup END

set fillchars=diff:\ ,stl:\ ,stlnc:\ ,vert:│             " Characters to use for the status line, folds and filler lines
"set fillchars=stl:\ ,stlnc:\ ,vert:\│,fold:-,diff:-
"·⌴…˽│➤►×ˑ▕—▸¬•⣿\║│

set showbreak=↪
set number                                                                                     " Absolute line numbering
set relativenumber                                                                 " Line numbering relative to cursor
set conceallevel=2
set concealcursor=nc


"
" 5.  SYNTAX, HIGHLIGHTING AND SPELLING                                                                             {{{1
"
syntax on                                                                                   " Enable syntax highlighting
set synmaxcol=1000                                                       " Don't syntax highlight lines longer than this
set hlsearch                                                                 " Search highlighting : Enabled by default.
set termguicolors
set colorcolumn=+1
autocmd FileType gitcommit setlocal spell
set spelllang=en_us


"
" 6.  MULTIPLE WINDOWS                                                                                              {{{1
"
set laststatus=2                                                                                 " Status line always-on
set hidden                                                                 " Allow buffer switching without saving files
set switchbuf=useopen,usetab                                                " Which window to use when switching buffers
set splitbelow                                                      " Open new split below current one when using :split
set splitright                                           " Open new split to the right of current one when using :vsplit


"
" 8.  TERMINAL                                                                                                      {{{1
"
set title                                                      " Set title of VIM window to <filename> (<filepath>) type
set titlestring=%t%(\ %M%)%(\ (%{expand(\"%:~:.:h\")})%)%(\ %a%)
set t_Co=256                                                                     " Enable use of 256 colors in terminals
set t_ut=                                                               "Disable Background Color Erase by clearing t_ut


"
" 12. MESSAGES AND INFO                                                                                             {{{1
"
set shortmess+=sI                                          " To avoid intro screen, search direction change notification
set report=0                          " Show a report when N lines were changed. report=0 thus means "show all changes"!
set belloff=all


"
" 14. EDITING TEXT                                                                                                  {{{1
"
set textwidth=120                                            " Line length above which to break a line. 0 => Don't break
set backspace=indent,eol,start        " Allow backspace to erase previously entered characters, autoindent, and newlines
set formatoptions+=j                                                        " Remove a comment leader when joining lines
set formatoptions+=n                                                                          " Recognize numbered lists
set complete-=i                                                                 " Do not scan current and included files
set complete+=kspell                                                           " Use the currently active spell checking
set completeopt-=preview                                            " Don't show extra information in the preview window
set completeopt+=menuone                                                       " Show popup menu even for a single match
set completeopt+=noinsert                                                        " Do not insert any text until selected
set completeopt+=noselect                                                               " Do not select a match on popup
set pumheight=20
set omnifunc=syntaxcomplete#Complete                             " Function for filetype-specific Insert mode completion
set showmatch                                                                                     " Show matching braces
set nojoinspaces                                   " Don't insert two spaces after a period with every joining of lines.


"
" 15. TABS AND INDENTING                                                                                            {{{1
"
set expandtab                                                                                 " Replace tabs with spaces
set softtabstop=-1                                         " No. of spaces to insert for a tab when expandtab is enabled
set shiftwidth=2                                                  " Set software tab-width (for eg in case of << and >>)
set shiftround                                                                 " Round to 'shiftwidth' for "<<" and ">>"
set autoindent                                                                                   " Auto-indent new lines
set cinkeys-=0#                                                          " Prevent forcing of C-preprocessor to column 1


"
" 16. FOLDING                                                                                                       {{{1
"
"set foldcolumn=3                                                               " Width of column used to indicate folds
set foldtext=utils#FoldText()
set foldmethod=marker
set foldnestmax=2                                      " Maximum fold depth for when 'foldmethod is "indent" or "syntax"


"
" 19. READING AND WRITING FILES                                                                                     {{{1
"

set fileformat=unix                                                                                         " EOL format
set backup                                                              " Create backup of files before overwriting them
execute 'set backupdir=' . g:dotvim . '/tmp/backups'
if !isdirectory(&backupdir) | call mkdir(&backupdir, 'p') | endif

set autoread


"
" 20. THE SWAP FILE                                                                                                 {{{1
"
set noswapfile


"
" 21. COMMAND LINE EDITING                                                                                          {{{1
"
set history=1000                                                                      " No. of command lines to remember
set wildmenu                                                           " Command-line completion shows a list of matches
set wildmode=list:longest,full                                  " Specifies command line completion to behave like shell

set undofile                                                             " Automatically save and restore undo history
execute 'set undodir=' . g:dotvim . '/tmp/undos'
" List of directories to save undofile
if !isdirectory(&undodir) | call mkdir(&undodir, 'p') | endif


"
" 23. RUNNING MAKE AND JUMPING TO ERRORS                                                                            {{{1
"
if executable('rg')
  set grepformat=%f:%l:%m
  let &grepprg='rg --vimgrep' . (&smartcase ? ' --smart-case' : '')
elseif executable('ag')
  set grepformat=%f:%l:%m
  let &grepprg='ag --vimgrep' . (&smartcase ? ' --smart-case' : '')
endif



"
" 26. VARIOUS                                                                                                       {{{1
"
execute 'set viewdir=' . g:dotvim . '/tmp/views'
" Directory to save views to
if !isdirectory(&viewdir) | call mkdir(&viewdir, 'p') | endif
set viminfo='20,<50                                                                 " What to write in the .viminfo file


"
" 27. MISC                                                                                                          {{{1
"
colorscheme catppuccin_frappe
" Netrw
let g:netrw_liststyle=3

" Autocommands                                                                                                      {{{2
if has('autocmd')
  " Resize split windows when size of xterm's window changes
  augroup Geometry
    autocmd!
    autocmd VimResized * wincmd =
  augroup END

  " Perforce related
  augroup Perforce
    autocmd!
    autocmd FileChangedRO * call perforce#Checkout("-prompt", expand('<afile>:p'))
  augroup END

  " Diff related
  augroup Diff
    autocmd!
    autocmd BufWritePost * if &diff | diffupdate | endif
    autocmd VimEnter * if &diff|call utils#SetFileTypesInDiff()|endif
  augroup END
endif
" }}}2
" }}}1


""" Local vimrc
if system('hostname') =~ '^atl'
  packadd work
endif
