let g:dotvim = expand('<sfile>:p:h')

let mapleader = "\<Space>"
let maplocalleader = "\\"

source $VIMRUNTIME/defaults.vim

" Overrides and additions beyond defaults.vim

" Moving around, searching
set nostartofline
set ignorecase
set smartcase

" Displaying text
set scrolloff=3
set sidescrolloff=10
set number
set relativenumber

" Syntax, highlighting
set hlsearch
set termguicolors
set signcolumn=yes

" Multiple windows
set hidden
set switchbuf=useopen,usetab
set splitbelow
set splitright
set autochdir

" Terminal
set title
set titlestring=%t%(\ %M%)%(\ (%{expand(\"%:~:.:h\")})%)%(\ %a%)

" Messages
set belloff=all
set nrformats-=octal

" Tabs and indenting
set expandtab
set softtabstop=-1
set shiftwidth=2
set shiftround

" Folding
set foldmethod=marker

" Performance
set ttimeoutlen=50
set updatetime=300

" Swap / undo
set noswapfile
set undofile
execute 'set undodir=' . g:dotvim . '/tmp/undos'
if !isdirectory(&undodir) | call mkdir(&undodir, 'p') | endif

" Command line
set wildmode=list:longest,full
if has('patch-8.2.0001')
  set wildoptions=pum
endif

" Vim 9+
if v:version >= 900
  set smoothscroll
  set splitkeep=screen
endif

" Grep
if executable('rg')
  set grepformat=%f:%l:%m
  let &grepprg='rg --vimgrep' . (&smartcase ? ' --smart-case' : '')
elseif executable('ag')
  set grepformat=%f:%l:%m
  let &grepprg='ag --vimgrep' . (&smartcase ? ' --smart-case' : '')
endif

" Misc
colorscheme catppuccin_frappe
let g:netrw_liststyle=3
autocmd FileType gitcommit setlocal spell spelllang=en_us

augroup Geometry
  autocmd!
  autocmd VimResized * wincmd =
augroup END
