Doom emacs private configuration

* Configuring Doom
Running =doom sync= is not required after modifying this file!

Some additional functions/macros to help configure Doom:
- =load!= for loading external *.el files relative to this one
- =use-package!= for configuring packages
- =after!= for running code after a package has loaded
- =add-load-path!= for adding directories to the `load-path', relative to this file. Emacs searches the `load-path' when you load packages with `require' or `use-package'.
- =map!= for binding new keys

To get information about any of these functions/macros, move the cursor over the highlighted symbol at press =K= (non-evil users must press =C-c c k=). This will open documentation for it, including demos of how they are used.

Also, =gd= (or =C-c c d=) will jump to their definition and see how they are implemented.

* General
Some functionality uses this to identify you, e.g. GPG configuration, email clients, file templates and snippets.
#+begin_src emacs-lisp
  (setq user-full-name "Kartik Shenoy")
#+end_src

** Better defaults
#+begin_src emacs-lisp
    (setq-default confirm-kill-emacs 'y-or-n-p  ; Confirm before quitting
  )
#+end_src

This determines the style of line numbers in effect. If set to
- `nil': line numbers are disabled.
- `'relative - relative line numbers
#+begin_src emacs-lisp
  (setq display-line-numbers-type 'relative)
#+end_src

** Fonts
Doom exposes five (optional) variables for controlling fonts in Doom. Here
are the three important ones:

- `doom-font'
- `doom-variable-pitch-font'
- `doom-big-font' -- used for `doom-big-font-mode'; use this for presentations or streaming.

They all accept either a font-spec, font string ("Input Mono-12"), or xlfd
font string. You generally only need these two:
#+begin_src emacs-lisp :tangle no
  (setq doom-font (font-spec :family "monospace" :size 12 :weight 'semi-light)
        doom-variable-pitch-font (font-spec :family "sans" :size 13))
#+end_src

** Themes
There are two ways to load a theme. Both assume the theme is installed and available.
You can either set `doom-theme' or manually load a theme with the `load-theme' function. This is the default:
#+begin_src emacs-lisp
  (setq doom-theme 'doom-one)
#+end_src

* Org
#+begin_src emacs-lisp
  (setq org-directory "~/Documents/Notes"
        org-default-notes-file (expand-file-name "Inbox.org" org-directory))
#+end_src
