#!/usr/bin/env bash
#
# AUTHOR: Kartik Shenoy
#
# DESCRIPTION:
# vile (VI-Less-Emulator)
# use vim like a pager

_cmd="vim -R -u ~/.vim/vimrc_pager -U NORC --noplugins"

if [[ -t 1 ]]; then
  if (( $# == 0 )); then
    if [[ -t 0 ]]; then
      echo "Missing filename" 1>&2
      exit
    fi
    eval "$_cmd -"
  else
    eval "$_cmd $@"
  fi
else
  # Output is not a terminal, cat arguments or stdin
  if (( $# == 0 )); then
    if [[ -t 0 ]]; then
      echo "Missing filename" 1>&2
      exit
    fi
    cat
  else
    cat "$@"
  fi
fi
