#!/usr/bin/env bash
#
# AUTHOR: Kartik Shenoy
#
# DESCRIPTION:
# vile (VI-Less-Emulator)
# use vim like a pager

_cmd="vim -R -u ~/.vim/vimrc_pager -U NORC --noplugins"

if [[ -n "${STEM}" ]]; then
  # ~/bin/vim -R --config NONE -u ~/.vim/vimrc_pager -c 'silent! /error:\|Backtrace:' -c 'set path=$STEM/build/latest,$STEM/build/latest/generated/ch,$STEM/build/latest/fake_c_incl/**,$STEM/ch/**,$STEM/import/avf/**' "$@"
  # FIXME: gf and find don't work when supplied with a relative path
  _cmd="$_cmd -c 'silent! /error:\|Stack Trace' -c 'silent! cd $STEM/build/latest' -c 'silent! set path=,,generated/ch,fake_c_incl/**,$STEM/ch/**,$STEM/import/avf/**'"
fi

if [[ -t 1 ]]; then
  if (( $# == 0 )); then
    if [[ -t 0 ]]; then
      echo "Missing filename" 1>&2
      exit
    fi
    eval "$_cmd -"
  else
    eval "$_cmd $@"
  fi
else
  # Output is not a terminal, cat arguments or stdin
  if (( $# == 0 )); then
    if [[ -t 0 ]]; then
      echo "Missing filename" 1>&2
      exit
    fi
    cat
  else
    cat "$@"
  fi
fi
