#!/usr/bin/env bash

# SetupMergeLayout() requires the files to be in the following order:
# 1 : base
# 2 : remote/theirs
# 3 : local/yours
# 4 : merged

${VISUAL:-${EDITOR:-vim}} -f -c "call perforce#MergeInit()" -c "set nobackup" "$@"
