#!/bin/bash

# SetupMergeLayout() requires the files to be in the following order:
# 1 : base
# 2 : remote/theirs
# 3 : local/yours
# 4 : merged

# Perforce:
# $1 : base
# $2 : remote/theirs
# $3 : local/yours
# $4 : merged
gvim -f -c "call perforce#MergeInit()" -c "set nobackup" -geometry 400x70+0+0 "$@"
