#!/usr/bin/env bash
## bashrc file for home

## Aliases
alias gp=globalprotect
amd_vpn() {
  # if command grep Connected <<< $(globalprotect show --status); then
  if command grep gpd0 <<< $(ifconfig -s) >& /dev/null; then
    echo "VPN is already connected"
  else
    globalprotect connect --portal vpn.amd.com --username kshenoy
  fi
  # /usr/NX/bin/nxplayer --session leostream.nxs &
}

## fzf: https://github.com/junegunn/fzf
[[ -d /opt/fzf ]] && export FZF_PATH=/opt/fzf

## Specific to root
__histfile_perm_update__() {
  if [[ -f $HISTFILE ]]; then
    echo "Changing permissions of HISTFILE..."
    chown kshenoy $HISTFILE
    chgrp kshenoy $HISTFILE
    chmod 640 $HISTFILE
  fi
}
trap __histfile_perm_update__ EXIT

## When leaving the console, clear the screen to increase privacy
if [[ "$SHLVL" = 1 ]]; then
  [[ -x /usr/bin/clear_console ]] && /usr/bin/clear_console -q
fi

alias doomacs='emacs --with-profile doom'
alias boot2win='sudo grub-reboot Windows && shutdown -r 0'
